

-- Anomalies from Checks  (UUID with Check that flagged anomoly)
select * from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_ANOMALIES order by 1

-- Quarantined Data
select * from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_BRONZE_LC_LOANS
select * from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_GOLD_LC_LOANS_STATE
---------------------------------------------
-- Show Remediated Data (Typoed LOAN STATUS)
-- Corrected Values in SILVER
select QUARANTINED.ID, QUARANTINED.loan_status QUARANTINED_LOAN_STATUS, SILVER.LOAN_STATUS SILVER_LOAN_STATUS
  from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_BRONZE_LC_LOANS QUARANTINED
  join MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_ANOMALIES ANOMALIES on QUARANTINED.anomaly_uuid = ANOMALIES.anomaly_uuid
  join MEDALLION_ARCHITECTURE_DEMO.DEMO.SILVER_LC_LOANS SILVER on QUARANTINED.ID = SILVER.ID
   and ANOMALIES.quality_check_tags = 'REMEDIATE'
   
-- Show Quarantined Only Data (Non INT IDs)
-- Does not exist in SILVER
select QUARANTINED.ID, SILVER.ID SILVER_ID
  from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_BRONZE_LC_LOANS QUARANTINED
  join MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_ANOMALIES ANOMALIES on QUARANTINED.anomaly_uuid = ANOMALIES.anomaly_uuid
  left join MEDALLION_ARCHITECTURE_DEMO.DEMO.SILVER_LC_LOANS SILVER on QUARANTINED.ID = SILVER.ID
   and ANOMALIES.quality_check_tags = 'QUARANTINE'   
   
  
-- Quarantined Data for GOLD
select QUALITY_CHECK_ID, SOURCE_CONTAINER, QUALITY_CHECK_MESSAGE, QUALITY_CHECK_RULE_TYPE,QUALITY_CHECK_TAGS, QUALITY_CHECK_PARAMETERS from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_ANOMALIES where source_container = 'GOLD_LC_LOANS_STATE'

-- shows Aggregated STATE, YEAR, LOAN_STATUS with AVG_INT_RATE >= 100%
select QUARANTINED.ANOMALY_UUID, QUARANTINED.ADDR_STATE, QUARANTINED.ISSUE_YEAR, QUARANTINED.AVG_INT_RATE
  from MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_GOLD_LC_LOANS_STATE QUARANTINED
  join MEDALLION_ARCHITECTURE_DEMO.DEMO._MEDALLION_SF_ANOMALIES ANOMALIES on QUARANTINED.anomaly_uuid = ANOMALIES.anomaly_uuid
   and ANOMALIES.quality_check_tags = 'QUARANTINE'   
